// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Secret struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	KvData []byte      `json:"kv_data"`
}
