// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: secret.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSecretByID = `-- name: DeleteSecretByID :exec
DELETE FROM secrets WHERE id = $1
`

func (q *Queries) DeleteSecretByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSecretByID, id)
	return err
}

const getScretsById = `-- name: GetScretsById :one
SELECT id, name, kv_data FROM secrets WHERE id = $1
`

func (q *Queries) GetScretsById(ctx context.Context, id pgtype.UUID) (Secret, error) {
	row := q.db.QueryRow(ctx, getScretsById, id)
	var i Secret
	err := row.Scan(&i.ID, &i.Name, &i.KvData)
	return i, err
}

const listAllSecrets = `-- name: ListAllSecrets :many
SELECT id, name, kv_data FROM secrets
`

func (q *Queries) ListAllSecrets(ctx context.Context) ([]Secret, error) {
	rows, err := q.db.Query(ctx, listAllSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Secret
	for rows.Next() {
		var i Secret
		if err := rows.Scan(&i.ID, &i.Name, &i.KvData); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putNewSecret = `-- name: PutNewSecret :exec
INSERT INTO secrets (id, name, kv_data) VALUES ($1, $2, $3)
`

type PutNewSecretParams struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	KvData []byte      `json:"kv_data"`
}

func (q *Queries) PutNewSecret(ctx context.Context, arg PutNewSecretParams) error {
	_, err := q.db.Exec(ctx, putNewSecret, arg.ID, arg.Name, arg.KvData)
	return err
}
